// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_loF6E20LaMN8WNRvhmz98LvLmBxu83g',
    appId: '1:162322167678:web:62114bb89f67c066cee52f',
    messagingSenderId: '162322167678',
    projectId: 'akdeniz-cep-eae6d',
    authDomain: 'akdeniz-cep-eae6d.firebaseapp.com',
    storageBucket: 'akdeniz-cep-eae6d.firebasestorage.app',
    measurementId: 'G-P5W7CPD6P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_EWm0y_YYxVy4kCIJ_cNQLqIQOEPUrwk',
    appId: '1:162322167678:android:0293df0816a5ba89cee52f',
    messagingSenderId: '162322167678',
    projectId: 'akdeniz-cep-eae6d',
    storageBucket: 'akdeniz-cep-eae6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhzwEuzqKPhPeJ1BkmkPX3Xt3mrjjT_XI',
    appId: '1:162322167678:ios:b7bb2816acdfa7a9cee52f',
    messagingSenderId: '162322167678',
    projectId: 'akdeniz-cep-eae6d',
    storageBucket: 'akdeniz-cep-eae6d.firebasestorage.app',
    iosBundleId: 'com.example.akdenizCep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhzwEuzqKPhPeJ1BkmkPX3Xt3mrjjT_XI',
    appId: '1:162322167678:ios:b7bb2816acdfa7a9cee52f',
    messagingSenderId: '162322167678',
    projectId: 'akdeniz-cep-eae6d',
    storageBucket: 'akdeniz-cep-eae6d.firebasestorage.app',
    iosBundleId: 'com.example.akdenizCep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_loF6E20LaMN8WNRvhmz98LvLmBxu83g',
    appId: '1:162322167678:web:44d22673848601e3cee52f',
    messagingSenderId: '162322167678',
    projectId: 'akdeniz-cep-eae6d',
    authDomain: 'akdeniz-cep-eae6d.firebaseapp.com',
    storageBucket: 'akdeniz-cep-eae6d.firebasestorage.app',
    measurementId: 'G-NLPQQRH1S9',
  );
}
